services:
  db:
    image: mysql:8.0.34
    container_name: mysql_db # Ensure this name isn't already taken, or remove old container
    restart: unless-stopped
    env_file:
      - .env # This makes DB_USERNAME, DB_PASSWORD, DB_DATABASE available
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Uses password from .env for root
      MYSQL_DATABASE: ${DB_DATABASE}      # Uses database name from .env
      MYSQL_USER: ${DB_USERNAME}          # Uses the new 'veltro_user' from .env
      MYSQL_PASSWORD: ${DB_PASSWORD}      # Uses password from .env for veltro_user
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'   # Fine for development, but set to 'no' in production
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: